
all:
	$(MAKE) -C libnx/
	$(MAKE) -C LibraryAppletHbTarget/
	$(MAKE) -C SystemApplicationHbTarget/

clean:
	$(MAKE) -C libnx/ clean
	$(MAKE) -C LibraryAppletHbTarget/ clean
	$(MAKE) -C SystemApplicationHbTarget/ clean